chore: atualiza workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Blog-REST-API-Node CI
 
 on:
@@ -16,10 +13,10 @@ jobs:
     strategy:
       matrix:
         node-version: [16.x, 18.x, 20.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
       - uses: actions/checkout@v3
+
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
@@ -28,7 +25,51 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run tests
+      - name: Run tests and update check status
         env:
-          MONGODB_URL: ${{ secrets.MONGODB_URL }} # Define a variável de ambiente para o MongoDB URL
-        run: npm run test
+          MONGODB_URL: ${{ secrets.MONGODB_URL }}
+        run: |
+          npm run test
+          if [ $? -eq 0 ]; then
+            echo "Tests passed"
+            echo "::set-output name=tests_passed::true"
+          else
+            echo "Tests failed"
+            echo "::set-output name=tests_passed::false"
+          fi
+
+      - name: Check test status and update branch protection
+        if: ${{ github.ref == 'refs/heads/develop' }}
+        uses: actions/github-script@v5
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const testsPassed = ${{ steps.run tests and update check status.outputs.tests_passed }};
+            const context = github.context;
+            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
+
+            const status = testsPassed ? 'success' : 'failure';
+            const sha = context.sha;
+            const repo = context.repo;
+
+            await octokit.repos.createCommitStatus({
+              ...repo,
+              sha: sha,
+              state: status,
+              context: 'CI/Test',
+            });
+
+            if (!testsPassed) {
+              console.log("Tests failed. Branch protection status will not be updated.");
+              return;
+            }
+
+            await octokit.repos.updateBranchProtection({
+              ...repo,
+              branch: 'develop',
+              enforce_admins: true,
+              required_status_checks: {
+                strict: true,
+                contexts: ['CI/Test'],
+              },
+            });
